export default {
  index: "Overview",
  versioning: "Versioning",
  "coordination-release-scope": "Coordination release scope",
  "coordination-v02": "GRP 0.2 contract",
  "coordination-candidate": "Reads, turns and presence",
  "actions-artifacts-candidate": "Actions and artifacts",
  transport: "Transport",
  rooms: "Rooms",
  decisions: "Decisions",
  mechanisms: "Mechanisms",
  mandates: "Mandates",
  receipts: "Receipts",
  discovery: "Discovery",
  errors: "Errors",
  schema: "Schema reference",
  "rest-api": "REST API (OpenAPI)",
  interop: "Interop",
  changelog: "Changelog",
};
