export default {
  index: "Introduction",
  safety: "Safety, risks, and limits",
  quickstart: "Quickstart",
  cli: "The CLI",
  "coordination-candidate": "Coordination candidate",
  "reading-and-recovery": "Reading and recovery",
  asynchronous: "Asynchronous rooms",
  organizations: "Organizations",
  "self-hosting": "Run your own host",
  "build-a-host": "Build a GRP host",
  architecture: "Architecture",
  concepts: "Concepts",
  sdk: { title: "SDKs", display: "hidden" },
};
